FROM node:20-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY apps/web/package.json apps/web/pnpm-lock.yaml* ./

RUN pnpm install

COPY apps/web .

EXPOSE 3001

CMD ["pnpm", "run", "dev", "--host", "0.0.0.0"]

